version: '3.8'

services:
  django:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - fastapi
    env_file:
      - .env
    networks:
      - backend_network

  fastapi:
    build: ./execution_service
    ports:
      - "8001:8001"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
