# Generated by Django 4.2.19 on 2025-02-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_challenge_userprogress_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
